[package]
name = "database_client"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/database_client.rs"

[dependencies]
anyhow.workspace = true
futures.workspace = true
http_client_tls.workspace = true
log.workspace = true
reqwest_client.workspace = true
rustls.workspace = true
rustls-platform-verifier.workspace = true
tokio.workspace = true
tokio-postgres.workspace = true
tokio-rustls.workspace = true
