[package]
name = "android_sdk"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/android_sdk.rs"

[dependencies]
anyhow.workspace = true
async-compression.workspace = true
async-tar.workspace = true
futures.workspace = true
gpui.workspace = true
http_client.workspace = true
image.workspace = true
log.workspace = true
paths.workspace = true
reqwest.workspace = true
reqwest_client.workspace = true
smol.workspace = true
util.workspace = true
